sudo: required

language: java

services:
  - docker

after_success:
  - docker build -t $DOCKER_IMAGE .
  - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_URL
  - docker push $DOCKER_IMAG
  - echo "$WEBHOOK_URL/?hook=$WEBHOOK_NAME&token=$WEBHOOK_TOKEN"
  - curl --data "" "$WEBHOOK_URL/?hook=$WEBHOOK_NAME&token=$WEBHOOK_TOKEN"
